kafka:
  host: "localhost"
  port: 29092
  topic: "test-topic-1"
  group-id: "my_group"
  auto-offset-reset: "earliest"
  enable-auto-commit: true

spark_hadoop:
  spark_master: "spark://spark-master:7077"
  hdfs_namenode: "hdfs://namenode:9000"
