[project]
name = "big-data-stack-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.12.1",
    "pyspark==3.5.1",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
]
